# Generated by Django 5.1.5 on 2025-01-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TriangleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("evaluation_date", models.DateField()),
                (
                    "earned_premium",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("reported_loss", models.DecimalField(decimal_places=2, max_digits=15)),
                ("paid_loss", models.DecimalField(decimal_places=2, max_digits=15)),
                ("program", models.CharField(max_length=100)),
                ("dev_lag", models.IntegerField()),
            ],
        ),
    ]
